bboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/urls.py
from django import template
from django.urls import path
from .views import index,other_page,BBLoginView,profile,BBLogoutView, ChangeUserInfoView, BBPasswordChangeView,RegisterUserView, RegisterDoneView,user_activate
from django.contrib.auth.views import LoginView
app_name = 'main'
urlpatterns = [
    path('<str:page>/',other_page, name='other'),
    path('',index,name='index'),
    path('accounts/profile/',profile,name='profile'),
    path('accounts/logout/',BBLogoutView.as_view(),name='logout'),
    path('accounts/login/',BBLoginView.as_view(),name='login'),
    path('accountss/login/',LoginView.as_view(template_name='main/loginn.html'),name='loginn'),
    path('accounts/profile/change/',ChangeUserInfoView.as_view(),name='profile_change'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(),name='password_change'),
    path('accounts/register/done/',RegisterDoneView.as_view(),name='register_done'),
    path('accounts/register/',RegisterUserView.as_view(),name='register'),
    path('accounts/register/activate/<str:sign>/',user_activate,name='register_activate'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True,db_index=True,verbose_name='Aktivlashgan')
    send_messages = models.BooleanField(default=True,verbose_name='Foydalanuvchiga kommentariyalarni yuborish mumkin')
    class Meta(AbstractUser.Meta):
        pass 

main/forms.py
from django import forms
from django.forms import fields, models
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .apps import user_registreted

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Elektron manzil')

    class Meta:
        model = AdvUser
        fields = {'username','email','first_name','last_name','send_messages'}

class RegistrerUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,label='Elektron manzil')
    password1 = forms.CharField(label='Parol',widget=forms.PasswordInput,help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Parol(qaytatdan)',widget=forms.PasswordInput,help_text='Parolni yuqorida kiritgan parolingizdek kiriting')
    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password_validation)
        return password1
    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1!=password2:
            errors = {'password2':ValidationError('Kiritilgan parollar mos tushmadi',code='password_mismatch')}
            raise ValidationError(errors)

    def save(self,commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registreted.send(RegistrerUserForm, instance=user)
        return user 
    class Meta:
        model = AdvUser
        fields = {'username','email','password1','password2','first_name','last_name','send_messages'}

main/views.py
from django import template
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.edit import UpdateView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import AdvUser
from .forms import ChangeUserInfoForm,RegistrerUserForm
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from .utilities import signer

def user_activate(request,sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request,'bad_signature.html')
    user = get_object_or_404(AdvUser,username=username)
    if user.is_activated:
        template = 'user_is_activated.html'
    else:
        template = 'activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request,template)
    
class RegisterDoneView(TemplateView):
    template_name = 'main:register_done.html'

class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'register_user.html'
    form_class = RegistrerUserForm
    success_url = reverse_lazy('main:register_done')

class BBPasswordChangeView(SuccessMessageMixin,LoginRequiredMixin,PasswordChangeView):
    template_name = 'password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Parol ozgardi'


class ChangeUserInfoView(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model = AdvUser
    template_name = 'change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Foydalanuvchi malumoti ozgardi'

    def setup(self,request,*args,**kwargs):
        self.user_id = request.user.pk
        return super().setup(request,*args,**kwargs)
    def get_object(self,queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset,pk=self.user_id)
class BBLogoutView(LoginRequiredMixin,LogoutView):
    template_name = 'main/logout.html'
# Create your views here.
@login_required
def profile(request):
    return render(request,'main/profile.html')
class BBLoginView(LoginView):
    template_name = 'main/login.html'
def index(request):
    return render(request,'main/index.html')

def other_page(request,page):
    try:
        template = get_template('main/'+page+'.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Asosiy{%endblock%}-E'lonlar doskasi</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css'%}">
    {% bootstrap_javascript jquery='slim'%}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">E'lonlar</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:register' %}">Registratsiya</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                href="#" role="button" aria-haspopup="true"
                aria-expanded="false">Profil</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'main:profile'%}">Mening e'lonlarim</a>
                    <a class="dropdown-item" href="{% url 'main:profile_change' %}">Ma'lumotlarni o'zgartirish</a>
                    <a class="dropdown-item" href="{% url 'main:password_change' %}">Parolni o'zgartirish</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'main:logout'%}">Chiqish</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="">O'chirish</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'main:loginn'%}">Kirish</a></li>
            {%endif%}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column border">
            <a class="nav-link root" href="{% url 'main:index' %}">Bosh sahifa</a>
            <a class="nav-link root" href="{% url 'main:other' page='about'%}">Sayt haqida</a>
            <span class="nav-link root font-weight-bold">Ko'chmas mulk</span>
            <a class="nav-link" href="#">Turar joy</a>
            <a class="nav-link" href="#">Omborlar</a>
            <a class="nav-link" href="#">Garajlar</a>
            <a class="nav-link" href="#">Hovli joy</a>
            <span class="nav-link root font-weight-bold">Transport</span>
            <a class="nav-link" href="#">Yengil</a>
            <a class="nav-link" href="#">Yuk mashinasi</a>
            <a class="nav-link" href="#">Mototsikl</a>
            <a class="nav-link" href="#">Suv transporti</a>
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages%}
            {% block content%}
            {% endblock%}
        </section>

    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy;SDeVPro</p>
    </footer>
    
</body>
</html>

main/templates/main/about.html
{%extends 'layout/basic.html'%}
{% block title %}Sayt haqida {%endblock%}
{%block content%}
<h2>Sayt haqida</h2>
<p>Bu sayt oldi sotdi uchun mo'ljallangan</p>
<p>Hamma huquqlar &laquo;SDeVPro&raquo; ga tegishli</p>
{%endblock%}

main/templates/main/activation_done.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Aktivlashish amalga oshdi {%endblock%}
{% block content%}
<h2>Aktivlashish </h2>
<p><a href="{% url 'main:login'%}">Saytga kirish</a></p>
{% endblock %}

main/templates/main/bad_signature.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Aktivlashish amalga oshmadi {%endblock%}
{% block content%}
<h2>Aktivlashish amalga oshmadi boshqatan registratsiyadan o'ting</h2>
<p><a href="{% url 'main:register'%}">Registratsiyadan o'tish</a></p>
{% endblock %}

main/templates/main/change_user_info.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Foydalanuvchi ma'lumotlarini o'zgartirish {%endblock%}
{% block content%}
<h2>Foydalanuvchi shaxsiy ma'lumotlarini o'zgartirish qismi {{user.username}}</h2>
<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal'%}
    {% buttons submit="Saqlash"%}{%endbuttons%}
</form>
{% endblock %}

main/templates/main/index.html
{% extends 'layout/basic.html'%}
{% block content %}
<h2>Oxirgi 10 ta e'lon</h2>
{%endblock%}

main/templates/main/login.html
{% extends 'layout/basic.html'%}
{% load bootstrap4 %}
{%block title%}Kirish{%endblock%}
{%block content%}
<h2>Kirish</h2>
{%if user.is_authenticated%}
<p>Siz kirishni amalga oshirdingiz</p>
{%else%}
<form method='POST' action="">
{% csrf_token%}
{% bootstrap_form form layout="horizontal"%}
<input type="hidden" name="next" value="{{next}}">
{%buttons submit="kirish"%}{%endbuttons%}
</form>
{%endif%}
{%endblock%}

main/templates/main/loginn.html
{% extends 'layout/basic.html'%}
{% load bootstrap4 %}
{%block title%}Kirish{%endblock%}
{%block content%}
<h2>Kirish</h2>
{%if user.is_authenticated%}
<p>Siz kirishni amalga oshirdingiz</p>
{%else%}
<form method='POST' action="">
{% csrf_token%}
{% bootstrap_form form layout="horizontal"%}
<input type="hidden" name="next" value="{{next}}">
{%buttons submit="kirish"%}{%endbuttons%}
</form>
{%endif%}
{%endblock%}

main/templates/main/logout.html
{%extends 'layout/basic.html' %}
{% block title%}Chiqish{%endblock%}
{%block content%}
<h2>Chiqish</h2>
<p>Siz saytdan chiqtingiz</p>
{%endblock%}

main/templates/main/password_change.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Foydalanuvchi parolini o'zgartirish {%endblock%}
{% block content%}
<h2>Foydalanuvchi parolini o'zgartirish qismi {{user.username}}</h2>
<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal'%}
    {% buttons submit="Parolni o'zgartirish"%}{%endbuttons%}
</form>
{% endblock %}

main/templates/main/profile.html
{%extends 'layout/basic.html'%}
{%block title%}Foydalanuvchi Profili{%endblock%}
{%block content%} 
<h2>Foydalanuvchi profili {{user.username}}</h2>
{%if user.first_name and user.last_name%}
<p>Salom {{user.first_name}} {{user.last_name}}</p>
{%else%}
<p>Salom</p>
{%endif%}
<h3>Sizning e'lonlaringiz</h3>
{%endblock%}

main/templates/main/register_done.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Registratsiya yakullandi {%endblock%}
{% block content%}
<h2>Registratsiya yakullandi</h2>
<p>Elektron manzilingizga aktivlashtirish uchun xat yuborildi</p>
{% endblock %}

main/templates/main/register_user.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Registratsiya {%endblock%}
{% block content%}
<h2>Registratsiya </h2>
<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal'%}
    {% buttons submit="Foydalanuvchi yaratish "%}{%endbuttons%}
</form>
{% endblock %}

main/templates/main/user_is_activated.html
{%extends 'layout/basic.html'%}
{% load bootstrap4 %}
{% block title%}Aktivlashish amalga oshirildi, rahmat {%endblock%}
{% block content%}
<h2>Aktivlashish amalga oshdi, rahmat </h2>
<p><a href="{% url 'main:login'%}">Saytga kirish</a></p>
{% endblock %}